# CNN implementation for recognition of MNIST hand written digit dataset

<b> Importing required libraries </b>

In [1]:
import pandas as pd
import numpy as np
import keras
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from sklearn.model_selection import train_test_split

Using TensorFlow backend.


<b> Importing data </b>

In [4]:
data = pd.read_csv(r'C:\Users\Ankit\Desktop\mnist.csv')

In [5]:
data.head()

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [6]:
data.iloc[3,1:].values.reshape(28,28).astype('uint8')

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  50, 224,   0,
          0,   0,   0,   0,   0,   0,  70,  29,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [7]:
#Storing Pixel array in form length width and channel in df_x
df_x = data.iloc[:,1:].values.reshape(len(data),28,28,1)

#Storing the labels in y
y = data.iloc[:,0].values

In [8]:
df_y = keras.utils.to_categorical(y,num_classes=10)

In [9]:
df_x = np.array(df_x)
df_y = np.array(df_y)

In [10]:
y

array([2, 1, 0, ..., 5, 6, 8], dtype=int64)

In [11]:
df_y

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [12]:
df_x.shape

(69999, 28, 28, 1)

In [13]:
x_train, x_test, y_train, y_test = train_test_split(df_x,df_y,test_size=0.2,random_state=4)

In [14]:
model = Sequential()
model.add(Convolution2D(32,3,data_format='channels_last',activation='relu',input_shape=(28,28,1)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(100))
model.add(Dropout(0.5))
model.add(Dense(10))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer = 'adadelta', metrics = ['accuracy'])

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 5408)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 100)               540900    
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1010      
_________________________________________________________________
activation_1 (Activation)    (None, 10)               

In [20]:
model.fit(x_train,y_train,validation_data=(x_test,y_test), epochs=10)

Train on 55999 samples, validate on 14000 samples
Epoch 1/10
55999/55999 [==============================] - 21s 379us/step - loss: 0.0591 - accuracy: 0.9835 - val_loss: 0.0865 - val_accuracy: 0.9791
Epoch 2/10
55999/55999 [==============================] - 22s 395us/step - loss: 0.0548 - accuracy: 0.9838 - val_loss: 0.0911 - val_accuracy: 0.9777
Epoch 3/10
55999/55999 [==============================] - 22s 398us/step - loss: 0.0494 - accuracy: 0.9863 - val_loss: 0.0916 - val_accuracy: 0.9796
Epoch 4/10
55999/55999 [==============================] - 22s 391us/step - loss: 0.0463 - accuracy: 0.9873 - val_loss: 0.0946 - val_accuracy: 0.9798
Epoch 5/10
55999/55999 [==============================] - 22s 401us/step - loss: 0.0438 - accuracy: 0.9873 - val_loss: 0.0967 - val_accuracy: 0.9816
Epoch 6/10
55999/55999 [==============================] - 22s 396us/step - loss: 0.0417 - accuracy: 0.9882 - val_loss: 0.0986 - val_accuracy: 0.9799
Epoch 7/10
55999/55999 [==============================] 

In [21]:
model.evaluate(x_test,y_test)

14000/14000 [==============================] - 1s 84us/step


[0.1095376308631629, 0.9777857065200806]